"""H0-B supervisor-owned ExecutionReceipt and product ValidationReceipt.

``ExecutionReceipt`` is generated by the supervisor from container run facts,
MCP broker events and an independent artifact scan — never from the
untrusted ``HarnessResult`` alone. ``ValidationReceipt`` is produced by the
product validator. Neither receipt may approve content, advance a Stage or
publish a Release.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import Field

from .manifest import ArtifactManifest
from .request import StrictContractModel
from .result import HarnessStatus


class ExitClassification(str, Enum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
    TIMED_OUT = "timed_out"
    ORPHANED = "orphaned"


class ToolCallSummary(StrictContractModel):
    tool: str = Field(min_length=1)
    calls: int = Field(ge=0)


class ExecutionReceipt(StrictContractModel):
    """Supervisor-owned execution evidence for exactly one attempt."""

    receipt_version: str = Field(default="1.0.0", pattern=r"^\d+\.\d+\.\d+$")
    execution_id: str = Field(min_length=1, max_length=200)
    spec_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    request_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    harness_id: str = Field(min_length=1, max_length=200)
    image_ref: str | None = None
    adapter_id: str | None = None
    status: HarnessStatus
    exit_classification: ExitClassification
    exit_code: int | None = None
    message: str = ""
    started_at: datetime
    ended_at: datetime
    budget_used: dict[str, int] = Field(default_factory=dict)
    event_summary: tuple[str, ...] = ()
    tool_call_summary: tuple[ToolCallSummary, ...] = ()
    artifact_manifest: ArtifactManifest
    retryable: bool = False
    validator_input: dict[str, object] = Field(default_factory=dict)


class ValidationReceipt(StrictContractModel):
    """Product validator evidence: validator identity + input hash + findings."""

    validator_id: str = Field(min_length=1)
    validator_version: str = Field(min_length=1)
    validator_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    input_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    result: Literal["passed", "failed"]
    findings: tuple[str, ...] = ()
