"""Governed clinical knowledge contracts and compatibility checks."""

from .compatibility import (
    ContractCompatibilityError,
    assert_contract_compatible,
    schema_bundle_sha256,
    verify_sha256,
)
from .client import (
    HttpKnowledgeTransport,
    KnowledgeServiceClient,
    KnowledgeServiceContractError,
    KnowledgeServiceUnavailable,
)
from .ae_rule_governance import (
    AERuleGovernanceError,
    RULE_GOVERNANCE_APPROVED_PATH,
    RULE_GOVERNANCE_REPORT_PATH,
    RULE_GOVERNANCE_REVIEW_ID,
    TARGET_KNOWLEDGE_ID,
    TARGET_RULE_ID,
    approve_ae_rule_governance_from_receipt,
    build_ae_rule_governance_report,
    build_clean_ae_rule_reuse_context,
    prepare_ae_rule_governance_review,
    validate_ae_rule_governance_report,
)
from .models import (
    ApprovalEvidence,
    ApprovalStatus,
    CapabilityId,
    CompatibilityRange,
    ContentStatus,
    ExecutionContext,
    FigureRecord,
    KnowledgeItem,
    PdfStatus,
    RightsStatus,
    RuntimeManifest,
    SourceRecord,
    StorageMode,
    StudyDecision,
    TEAEWindowRule,
    WorkflowStage,
    WorkflowPlaybook,
    is_approval_status_transition_allowed,
    is_content_status_transition_allowed,
    is_pdf_status_transition_allowed,
)
from .promotion import (
    PromotionCandidate,
    PromotionCandidateArtifact,
    PromotionCandidateError,
    PromotionReviewStatus,
    create_promotion_candidate,
)
from .resolver import ContextResolutionError, KnowledgeContextResolver
from .snapshot import LockedSnapshot, SnapshotError, load_locked_snapshot
from .study_decisions import (
    StudyDecisionError,
    load_study_decisions,
    project_study_decision,
)

__all__ = [
    "ContractCompatibilityError",
    "ContextResolutionError",
    "HttpKnowledgeTransport",
    "ApprovalStatus",
    "AERuleGovernanceError",
    "ApprovalEvidence",
    "CapabilityId",
    "CompatibilityRange",
    "ContentStatus",
    "ExecutionContext",
    "FigureRecord",
    "KnowledgeItem",
    "KnowledgeContextResolver",
    "KnowledgeServiceClient",
    "KnowledgeServiceContractError",
    "KnowledgeServiceUnavailable",
    "LockedSnapshot",
    "PdfStatus",
    "PromotionCandidate",
    "PromotionCandidateArtifact",
    "PromotionCandidateError",
    "PromotionReviewStatus",
    "RULE_GOVERNANCE_APPROVED_PATH",
    "RULE_GOVERNANCE_REPORT_PATH",
    "RULE_GOVERNANCE_REVIEW_ID",
    "RightsStatus",
    "RuntimeManifest",
    "SourceRecord",
    "SnapshotError",
    "StorageMode",
    "StudyDecision",
    "StudyDecisionError",
    "TARGET_KNOWLEDGE_ID",
    "TARGET_RULE_ID",
    "TEAEWindowRule",
    "WorkflowStage",
    "WorkflowPlaybook",
    "assert_contract_compatible",
    "approve_ae_rule_governance_from_receipt",
    "build_ae_rule_governance_report",
    "build_clean_ae_rule_reuse_context",
    "create_promotion_candidate",
    "is_approval_status_transition_allowed",
    "is_content_status_transition_allowed",
    "is_pdf_status_transition_allowed",
    "schema_bundle_sha256",
    "load_locked_snapshot",
    "load_study_decisions",
    "prepare_ae_rule_governance_review",
    "project_study_decision",
    "validate_ae_rule_governance_report",
    "verify_sha256",
]
