"""Governed hybrid retrieval application boundary."""

from .contracts import (
    CapabilityState,
    ChannelCandidate,
    ChannelCapability,
    ChannelContribution,
    Citation,
    ExplicitGap,
    FusionPolicy,
    GapKind,
    QueryPlan,
    ReleaseScope,
    RetrievalChannel,
    RetrievalChannelUnavailable,
    RetrievalFilters,
    RetrievalHit,
    RetrievalNotFoundError,
    RetrievalRequest,
    RetrievalResult,
    RetrievalVisibility,
    RetrievalVisibilityError,
    RevisionDocument,
    RevisionTrace,
)
from .service import (
    HybridRetrievalService,
    RetrievalRepository,
    VectorCandidateProvider,
    VectorProviderStatus,
)
from .repository import SqlAlchemyRetrievalRepository

__all__ = [
    "CapabilityState",
    "ChannelCandidate",
    "ChannelCapability",
    "ChannelContribution",
    "Citation",
    "ExplicitGap",
    "FusionPolicy",
    "GapKind",
    "HybridRetrievalService",
    "QueryPlan",
    "ReleaseScope",
    "RetrievalChannel",
    "RetrievalChannelUnavailable",
    "RetrievalFilters",
    "RetrievalHit",
    "RetrievalNotFoundError",
    "RetrievalRepository",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievalVisibility",
    "RetrievalVisibilityError",
    "RevisionDocument",
    "RevisionTrace",
    "SqlAlchemyRetrievalRepository",
    "VectorCandidateProvider",
    "VectorProviderStatus",
]
