"""P17 release-candidate retrieval public API."""

from .contracts import (
    CandidateSearchRecord,
    CapabilityState,
    ChunkExplanation,
    ContextPackage,
    EvidenceCitation,
    ReleaseCandidateScope,
    ReleasedContextPackage,
    ReleasedRetrievalRequest,
    ReleasedRetrievalResult,
    RetrievalCapabilities,
    RetrievalHit,
    RetrievalQuery,
    RetrievalResult,
    RouteContributions,
    retrieval_query_identity,
    released_retrieval_query_identity,
)
from .service import (
    CandidateSearchRepositoryPort,
    FUSION_VERSION,
    ImmutableReleaseRetrievalService,
    ReleasedSearchRepositoryPort,
    RetrievalService,
)

__all__ = [
    "CandidateSearchRecord",
    "CandidateSearchRepositoryPort",
    "CapabilityState",
    "ChunkExplanation",
    "ContextPackage",
    "EvidenceCitation",
    "FUSION_VERSION",
    "ImmutableReleaseRetrievalService",
    "ReleaseCandidateScope",
    "ReleasedContextPackage",
    "ReleasedRetrievalRequest",
    "ReleasedRetrievalResult",
    "ReleasedSearchRepositoryPort",
    "RetrievalCapabilities",
    "RetrievalHit",
    "RetrievalQuery",
    "RetrievalResult",
    "RetrievalService",
    "RouteContributions",
    "retrieval_query_identity",
    "released_retrieval_query_identity",
]
